package com.example.medihelp;

/**
 * Created by abc on 27-02-2016.
 */
public class InputAddress {
    public static String[] STATES = {" ", "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal", ""};
    public static String[][] DISTRICTS = new String[][]{
            {" "},
            {" ", "South Andaman"},
            {" ", "Hyderabad",
                    "Secunderabad",
                    "Godavari",
                    "Krishna",
                    "Visakhapatnam"
            },
            {" ",
                    "Upper Subansiri",
                    "lower Subansiri",
                    "Tawang"
            },
            {" ",
                    "Barpeta",
                    "Dibrugarh",
                    "Cachar",
                    "Kamrup",
                    "Jorhat",
                    "Sonitpur"
            },
            {" ",
                    "Muzaffarpur",
                    "Darbhanga",
                    "Gaya",
                    "Patna"
            },
            {" ",
                    "Chandigarh"
            },
            {" ",
                    "Durg",
                    "Bilaspur",
                    "Bastar",
                    "Raipur"
            },
            {" ",
                    "Dadra and Nagar"
            },
            {" ",
                    "Daman"
            },
            {" ",
                    "North West Delhi",
                    "West Delhi",
                    "East Delhi",
                    "South West delhi",
                    "North Delhi",
                    "South Delhi",
                    "South West Delhi",
                    "Central Delhi",
                    "East delhi",
                    "North East Delhi",
                    "central Delhi",
                    "South East Delhi",
                    "New Delhi",
                    "EAST Delhi"
            },
            {" ",
                    "South Goa",
                    "Goa",
                    "North Goa"
            },
            {" ",
                    "Ahmedabad",
                    "Anand",
                    "Bharuch",
                    "Bhavnagar",
                    "Godhra",
                    "Jamnagar",
                    "Rajkot",
                    "Surat",
                    "Surendranagar",
                    "Vadodara"
            },
            {" ",
                    "Hisar",
                    "Ambala",
                    "Bhiwani",
                    "Faridabad",
                    "Palwal",
                    "Yamunanagar",
                    "Gurgaon",
                    "Fatehabad",
                    "Tohana",
                    "Jhajjar",
                    "Jind",
                    "Karnal",
                    "Kurukshetra",
                    "Mahendergarh",
                    "Narnaul",
                    "Panchkula",
                    "Panipat",
                    "Rewari",
                    "Rohtak",
                    "Sirsa",
                    "Sonipat"
            },
            {" ",
                    "Kangra",
                    "Shimla"
            },
            {" ",
                    "Jammu",
                    "Srinagar"
            },
            {" ",
                    "Hazaribagh",
                    "Jamshedpur",
                    "Ranchi"
            },
            {" ",
                    "Bangalore",
                    "Bengaluru",
                    "Mangalore"
            },
            {" ",
                    "Alappuzha",
                    "Cochin",
                    "Kannur",
                    "Karakonam",
                    "Kochi",
                    "Kolencherry",
                    "Kollam",
                    "Kottayam",
                    "Kozhikode",
                    "Modakkallur",
                    "Palakkad",
                    "Pathanamthitta",
                    "Perintalmanna",
                    "Thiruvalla",
                    "Thiruvananthapuram",
                    "Thrissur",
                    "Venjaramoodu"
            },
            {" ",
                    "Kavaratti"
            },
            {" ",
                    "Indore"
            },
            {" ",
                    "Mumbai",
                    "Pune",
                    "Thane"
            },
            {" ",
                    "Imphal",
                    "Manipur"
            },
            {" ",
                    "Shillong"
            },
            {" ",
                    "Aizawl"
            },
            {" ",
                    "Kohima"
            },
            {" ",
                    "Behrampur",
                    "Bhubaneswar",
                    "Burla",
                    "Cuttack",
                    "Rourkela"
            },
            {" ",
                    "Gorimedu",
                    "Kalapet",
                    "Kudupakkam",
                    "Madagadipet",
                    "Pangoor",
                    "Pillaiyarkuppam",
                    "Puducherry"
            },
            {" ",
                    "Ambala",
                    "Amritsar",
                    "Hoshiarpur",
                    "Jalandhar",
                    "Ludhiana",
                    "Mohali",
                    "Panchkula",
                    "Patiala",
                    "Ropar",
                    "Zirakpur"
            },
            {" ",
                    "Ajmer",
                    "Jaipur",
                    "Jodhpur"
            },
            {" ",
                    "Gangtok"
            },
            {" ",
                    "Chennai",
                    "Kanyakumari",
                    "Colachel",
                    "Nagercoil",
                    "Chinna",
                    "Seeragapadi",
                    "Vellore"
            },
            {" ",
                    "Agartala"
            },
            {" ",
                    "Agra",
                    "Ghaziabad",
                    "Greater",
                    "Noida",
                    "Hathras",
                    "Kanpur",
                    "Lucknow",
                    "Meerut",
                    "Moradabad",
                    "Muzaffarnagar",
                    "Saharanpur",
                    "Varanasi"
            },
            {" ",
                    "Dehradun",
                    "Haldwani",
                    "Rishikesh",
                    "Roorkee"
            },
            {" ",
                    "Kolkata"
            }
    };
}
